### PR TITLE
list of projects.

### LINKED ISSUE #6: Adding a section to feature projects.
We will soon make our projects public, so we need a section to display a list of projects for the community to contribute.

Related to - #5

### PR DESCRIPTION
**Pull request by sourabhsharma24**
try to resolve #6.

### CODE REVIEW

**Comment by AdarshRawat1** [comment]
@sourabh1111111 are you trying to contribute to this project? 
Actually you have opened an issue in your repository. In order to contribute to the project, fork the repository, pick an issue and try solving it. Once you are done with the changes, open a PR and we'll be happy to merge your PR. 
Thank you !

**Comment by CodeTorso** [comment]
Why is this PR serves as a commit history to all the other commits.

**Comment by sourabhsharma24** [comment]
Hi Code Torso,
Thank you for your message and for your patience. I'm relatively new to GitHub, and I've never encountered the situation you mentioned. From what I've learned, when a PR has multiple commits, it can serve as a summary of those changes, which is a Git best practice for maintaining a clean commit history. If you have more insights, I'd appreciate your guidance and you can it out once  more.

**Comment by CodeTorso** [comment]
Hey,
This thing causes as GitHub helps us understand what changes has happened into the repo when the PR was created until it was merged. Since your PR was the first but merged just 3 days ago. All the PRs that got merged in between that time period are shown here.

**Comment by sourabhsharma24** [comment]
Hi Code Torso,
Thank you for clarifying that. I appreciate your patience in helping me understand how GitHub handles commit history and PRs.  I'm grateful for the insights you've shared, and I'll keep this in mind for future contributions to maintain a clean and informative commit history.
Once again, thank you for your help .

**Comment by CodeTorso** [comment]
I have seen that open source is full of kind people. Chill. We are here doing something for no reason. Then why thanks 😃😃

**Pull request merged**
